// Issue #725: regenerates AvalonSdk/Generated.cs from docs/generated/openapi.json.
// Run via `dotnet run --project csharp/codegen` from this repo's root (moved
// here from avalon-protocol's bindings/csharp by issue #775 — see that
// repo's own Makefile history for the make csharp-sdk-types targets this
// used to be wired into there).
//
// Tool choice: NSwag's CSharpClientGenerator (DTO-only mode — GenerateClientClasses
// and GenerateClientInterfaces both false, so only request/response POCOs come out,
// not a full HTTP client; this SDK's HTTP layer is hand-written and stays that way,
// per the ticket's "smart client behavior stays hand-written" invariant). Verified
// live against the real docs/generated/openapi.json in this sandbox before picking
// it — NSwag/NJsonSchema were the only realistic candidates with mature C#-POCO
// output; Kiota targets full typed clients, not a DTO-only mode.
//
// Two fixups applied on top of NSwag's own output, both found by running it for
// real against this schema rather than assumed from its docs:
//
// 1. NJsonSchema 11.6.1's default C# property-name conversion only uppercases a
//    schema property name's first character (`created_at` -> `Created_at`), not
//    each underscore-delimited word — so left alone, every wire field name would
//    surface as non-idiomatic C#. PascalizeIdentifiers() below reformats each
//    property identifier in the generated source to real PascalCase
//    (`Created_at` -> `CreatedAt`) while leaving each property's
//    [JsonPropertyName("created_at")] attribute (the actual wire contract)
//    untouched — this is the "ergonomic, not just mechanically correct" bar the
//    ticket sets for this SDK.
// 2. None of these schemas set `additionalProperties: false`, so JSON Schema's own
//    default (additional properties allowed) would make NSwag emit an
//    AdditionalProperties dictionary + backing field on every single DTO — pure
//    boilerplate noise this SDK's hand-written types never had. Disabled per-schema
//    before generation (AllowAdditionalProperties = false) rather than left in.
using System.Linq;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using NJsonSchema.CodeGeneration.CSharp;
using NSwag;
using NSwag.CodeGeneration.CSharp;

string ThisDirectory([System.Runtime.CompilerServices.CallerFilePath] string path = "") =>
    System.IO.Path.GetDirectoryName(path)!;

var repoRoot = System.IO.Path.GetFullPath(System.IO.Path.Combine(ThisDirectory(), "..", ".."));
var schemaPath = System.IO.Path.Combine(repoRoot, "docs", "generated", "openapi.json");
var outPath = System.IO.Path.Combine(repoRoot, "csharp", "AvalonSdk", "Generated.cs");

var schemaJson = ExcludeUnrepresentableSchemas(System.IO.File.ReadAllText(schemaPath));
var doc = await OpenApiDocument.FromJsonAsync(schemaJson);

// Fixup 2 (see header): additionalProperties defaults to allowed in JSON Schema;
// none of these schemas opt out, so disable it explicitly rather than emit a
// noisy AdditionalProperties dictionary + backing field on every DTO.
foreach (var schema in doc.Components.Schemas.Values)
{
    schema.AllowAdditionalProperties = false;
    schema.AdditionalPropertiesSchema = null;
}

var settings = new CSharpClientGeneratorSettings
{
    ClassName = "Unused",
    GenerateClientClasses = false,
    GenerateClientInterfaces = false,
    GenerateDtoTypes = true,
    GenerateExceptionClasses = false,
};
settings.CSharpGeneratorSettings.Namespace = "Avalon.Sdk.Generated";
settings.CSharpGeneratorSettings.JsonLibrary = CSharpJsonLibrary.SystemTextJson;
settings.CSharpGeneratorSettings.ClassStyle = CSharpClassStyle.Poco;
settings.CSharpGeneratorSettings.GenerateOptionalPropertiesAsNullable = true;
settings.CSharpGeneratorSettings.GenerateNullableReferenceTypes = true;
settings.CSharpGeneratorSettings.GenerateDataAnnotations = false;
settings.CSharpGeneratorSettings.GenerateDefaultValues = false;
settings.CSharpGeneratorSettings.PropertyNameGenerator = new CSharpPropertyNameGenerator();

var generator = new CSharpClientGenerator(doc, settings);
var code = generator.GenerateFile();
code = PascalizeIdentifiers(code);

var header =
    "// <auto-generated>\n" +
    "// Generated by `make csharp-sdk-types` (bindings/csharp/codegen) from\n" +
    "// docs/generated/openapi.json — do not hand-edit, regenerate instead.\n" +
    "// </auto-generated>\n\n";
// NSwag's own "auto-generated" banner is replaced by ours above, so a diff against
// the checked-in file (csharp-sdk-types-check) isn't sensitive to NSwag/NJsonSchema
// version-string noise in that banner.
code = Regex.Replace(code, @"^//-+\r?\n// <auto-generated>\r?\n.*\r?\n// </auto-generated>\r?\n//-+\r?\n\r?\n", "", RegexOptions.Singleline);
code = header + code;

var version = doc.Info.Version;
code +=
    "\nnamespace Avalon.Sdk\n{\n" +
    "    public sealed partial class AvalonClient\n    {\n" +
    "        /// <summary>Issue #735/#725: the docs/generated/openapi.json `info.version`\n" +
    "        /// this file's generated types were produced from — generated straight from\n" +
    "        /// the same schema file, so it can't drift by construction.</summary>\n" +
    $"        public const string OpenApiSchemaVersion = {ToCSharpStringLiteral(version)};\n" +
    "    }\n}\n";

System.IO.File.WriteAllText(outPath, code);
Console.WriteLine($"wrote {outPath} ({code.Length} chars, schema version {version})");

static string ToCSharpStringLiteral(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

// A `oneOf` schema (a Rust enum with data, e.g. AuthenticityResponse's
// authentic/not_authentic variants) has no flat-POCO representation NSwag's
// C# generator can produce — left in, it silently emits an empty class with
// none of the variants' real fields (found by running the generator for real
// against this schema, not assumed). Since nothing in AvalonSdk's
// hand-written account/protocol surface consumes any of these today (the
// achievements bulk-issue/authenticity surface isn't ported to this SDK
// yet), they're stubbed out to a plain `{"type": "object"}` placeholder
// in-place before generation, rather than deleted — deleting would leave
// dangling $refs from every other schema (and operation) that legitimately
// points at them, which fails to parse at all. Left as a real (if empty)
// generated class, matching this file's public surface staying inert for a
// type nothing hand-written references, plus a console note on every
// regeneration so a newly-added oneOf schema doesn't silently degrade this
// way unnoticed.
static string ExcludeUnrepresentableSchemas(string rawJson)
{
    var root = JsonNode.Parse(rawJson)!.AsObject();
    var schemas = root["components"]!["schemas"]!.AsObject();

    var oneOfNames = schemas.Where(kv => kv.Value!["oneOf"] is not null).Select(kv => kv.Key).ToList();
    if (oneOfNames.Count > 0)
    {
        Console.WriteLine("stubbed out (oneOf, unrepresentable as a flat C# POCO, unused by AvalonSdk today): " + string.Join(", ", oneOfNames.OrderBy(n => n)));
    }
    foreach (var name in oneOfNames)
    {
        schemas[name] = new JsonObject { ["type"] = "object" };
    }
    return root.ToJsonString();
}

// Reformats every generated `public <Type> <Identifier> { get; set; }`-shaped
// property declaration whose identifier contains an underscore (NJsonSchema left
// it as `Created_at` etc. — see this file's header) into real PascalCase
// (`CreatedAt`). Deliberately scoped to property-declaration lines only, via the
// trailing `{ get; set; }` (or `{ get; init; }`) anchor, so it never touches a
// JsonPropertyName string literal or an XML doc comment.
static string PascalizeIdentifiers(string code)
{
    var propertyLine = new Regex(
        @"^(?<indent>\s*)(?<modifiers>public\s+[^\s]+\s+)(?<name>[A-Za-z0-9]+(?:_[A-Za-z0-9]+)+)(?<rest>\s*\{\s*get;\s*(set|init);\s*\}.*)$",
        RegexOptions.Multiline);
    return propertyLine.Replace(code, m =>
    {
        var pascal = string.Concat(m.Groups["name"].Value.Split('_').Select(word =>
            word.Length == 0 ? "" : char.ToUpperInvariant(word[0]) + word.Substring(1)));
        return $"{m.Groups["indent"].Value}{m.Groups["modifiers"].Value}{pascal}{m.Groups["rest"].Value}";
    });
}
