version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "developer-experience"
    commit-message:
      prefix: "[noissue] - "
    groups:
      cargo-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "nuget"
    directory: "/languages/csharp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "developer-experience"
    commit-message:
      prefix: "[noissue] - "
    groups:
      nuget-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/languages/typescript"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "developer-experience"
    commit-message:
      prefix: "[noissue] - "
    groups:
      npm-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "developer-experience"
    commit-message:
      prefix: "[noissue] - "
    groups:
      github-actions-all:
        patterns: ["*"]
